// Assemble all digitized overlay defs into src/ui/chartOverlays.ts.
// Inputs: out_dn_family.json (11 defs) + optional out_*.json from the bespoke
// chart agents (por20/por22/lith1/lith2/lith6). node assemble.mjs [dest]
import { readFileSync, writeFileSync, existsSync } from "fs";

const dest = process.argv[2] || "D:\\XX. SandiBumi\\src\\ui\\chartOverlays.ts";
const defs = [];
const seen = new Set();
const files = ["out_dn_family.json", "out_por20.json", "out_por22.json", "out_lith1.json", "out_lith2.json", "out_lith6.json"];
for (const f of files) {
  if (!existsSync(f)) { console.log(`skip ${f} (missing)`); continue; }
  const arr = JSON.parse(readFileSync(f, "utf8"));
  for (const d of Array.isArray(arr) ? arr : [arr]) {
    if (seen.has(d.id)) { console.log(`dup id ${d.id} skipped`); continue; }
    seen.add(d.id);
    if (d.xAxis === "pe") d.xAxis = "pef";
    if (d.yAxis === "pe") d.yAxis = "pef";
    defs.push(d);
  }
}
const r4 = v => Math.round(v * 1e4) / 1e4;
const fmtCurve = c => `{ name: ${JSON.stringify(c.name)}, labelEvery: ${c.labelEvery ?? 5}, grads: [${c.grads.map(g => `[${g[0]},${r4(g[1])},${r4(g[2])}]`).join(",")}] }`;
const fmtPoint = p => `{ x: ${r4(p.x)}, y: ${r4(p.y)}, label: ${JSON.stringify(p.label)} }`;
const fmtLine = l => `{ pts: [${l.pts.map(q => `[${r4(q[0])},${r4(q[1])}]`).join(",")}]${l.label ? `, label: ${JSON.stringify(l.label)}` : ""}${l.dash ? ", dash: true" : ""} }`;
const fmtRegion = g => `{ poly: [${g.poly.map(q => `[${r4(q[0])},${r4(q[1])}]`).join(",")}], label: ${JSON.stringify(g.label)} }`;

let ts = `// GENERATED by tools/chartdig (assemble.mjs) — do not edit by hand.
// Digitized from Schlumberger Log Interpretation Charts 2013 at vector precision
// (graduation-dash tips, grid-index calibration; every curve validated: consecutive
// graduations, long dashes on 5-multiples, worked examples). Neutron values are
// v/v; DT us/ft; densities g/cc; Pe, K %, Th ppm, Th/K, Umaa in chart units.
export type AxisKind = "neutron" | "density" | "dt" | "pef" | "k" | "th" | "thk" | "umaa" | "rhomaa";

export interface OverlayCurve { name: string; labelEvery: number; grads: [number, number, number][] }
export interface OverlayPoint { x: number; y: number; label: string }
export interface OverlayLine { pts: [number, number][]; label?: string; dash?: boolean }
export interface OverlayRegion { poly: [number, number][]; label: string }
export interface ChartOverlayDef {
  id: string;
  label: string;
  xAxis: AxisKind;
  yAxis: AxisKind;
  curves?: OverlayCurve[];
  points?: OverlayPoint[];
  lines?: OverlayLine[];
  regions?: OverlayRegion[];
  /** Draw dashed iso-graduation connectors across the curves. */
  isoConnect?: boolean;
  /** This chart's x axis is logarithmic (e.g. Th/K ratio) — drawn only when the
   *  matching plot axis is in log mode. */
  xLogNeeded?: boolean;
}

/** Curve mnemonics accepted for each chart axis (uppercased exact match). The
 *  tool-specific chart choice (CNL vs APS vs EcoScope...) stays the user's call —
 *  any neutron-family mnemonic gates any neutron-axis chart. */
export const AXIS_ALIASES: Record<AxisKind, string[]> = {
  neutron: ["NPHI", "TNPH", "NPOR", "PHIN", "CNC", "BPHI", "APLC", "FPLC", "CNL", "NPHI_COR"],
  density: ["RHOB", "RHOZ", "DEN", "ROBB", "DENB", "RHOB_COR"],
  dt: ["DT", "DTC", "DTCO", "AC", "DTL", "DT4P"],
  pef: ["PEF", "PE", "PEFZ", "PEF8"],
  k: ["POTA", "K", "HFK", "POTASSIUM"],
  th: ["THOR", "TH", "HTHO", "THORIUM"],
  thk: ["THK", "TH_K", "THPOTA", "THK_RATIO"],
  umaa: ["UMAA", "UMA"],
  rhomaa: ["RHOMAA", "RHOMA", "RHGA", "RHGX"],
};

export const CHART_OVERLAYS: ChartOverlayDef[] = [
`;
for (const d of defs) {
  ts += `  {\n    id: ${JSON.stringify(d.id)},\n    label: ${JSON.stringify(d.label)},\n    xAxis: ${JSON.stringify(d.xAxis)},\n    yAxis: ${JSON.stringify(d.yAxis)},\n`;
  if (d.curves?.length) ts += `    curves: [\n${d.curves.map(c => `      ${fmtCurve(c)},`).join("\n")}\n    ],\n`;
  if (d.points?.length) ts += `    points: [${d.points.map(fmtPoint).join(", ")}],\n`;
  if (d.lines?.length) ts += `    lines: [\n${d.lines.map(l => `      ${fmtLine(l)},`).join("\n")}\n    ],\n`;
  if (d.regions?.length) ts += `    regions: [\n${d.regions.map(g => `      ${fmtRegion(g)},`).join("\n")}\n    ],\n`;
  if (d.isoConnect) ts += `    isoConnect: true,\n`;
  if (d.xLogNeeded) ts += `    xLogNeeded: true,\n`;
  ts += `  },\n`;
}
ts += `];\n\nexport function findChartOverlay(id: string): ChartOverlayDef | undefined {\n  return CHART_OVERLAYS.find((d) => d.id === id);\n}\n`;
writeFileSync(dest, ts);
console.log(`wrote ${dest}: ${defs.length} defs (${defs.map(d => d.id).join(", ")}), ${Math.round(ts.length / 1024)} KB`);
