/**
 * Chart-overlay distribution policy — DEC-078 … DEC-082 (2026-08-19), SB-PLT-024.
 *
 * NOT generated. `chartOverlays.ts` is generated by `tools/chartdig` and must never be
 * hand-edited outside a ruled operation; this module is the hand-maintained policy
 * register beside it.
 *
 * How the 19 vendor-digitized chart definitions were resolved (verbatim rulings in
 * docs/takeover/DECISIONS.md; register history in docs/IP_PROVENANCE.md §2.1):
 *
 * - SIX definitions are DERIVED (DEC-078/079): their geometry is computed by
 *   `tools/gen-derived-overlays.mjs` from published equations and cited printed
 *   constants, proven against the digitized chart by `tools/chart-derivation.test.mjs`.
 *   Their entries below in `chartOverlays.ts` persist only for the parts the
 *   derivation deliberately keeps digitized (apparent-position points, keep-listed
 *   annotation lines); the derived data shadows the rest at resolution.
 *
 * - THIRTEEN definitions had NO independent primary source in principle — nine pure
 *   tool-response charts (DEC-078), Por-20's two defs (DEC-080, CNL-coupled neutron
 *   axis) and Lith-1's two defs (DEC-081, vendor-synthesis mineral ranges whose whole
 *   cited chain was read and prints no numeric values). They were retained cited and
 *   fail-closed for field verification until Jauhar delivered the Gate 5 word on
 *   2026-08-19 (DEC-082): DELETE. The thirteen entries were removed from
 *   `chartOverlays.ts` the same day. The list below is now the DELETION RECORD:
 *   `tools/chart-derivation.test.mjs` pins that none of these ids ever reappears in
 *   the overlay catalog and that the six derived ids all remain. The deleted bytes
 *   survive only in git history, which is the record DEC-078 requires.
 *
 * The overlay picker and renderer tolerate an absent id by design — nothing else in
 * the app changed when the thirteen left.
 */
import { CHART_OVERLAYS, findChartOverlay, type ChartOverlayDef } from "./chartOverlays";
import { DERIVED_CHART_OVERLAYS } from "./chartOverlaysDerived.gen";

/** DEC-082 deletion record: vendor definitions removed from the catalog, never to return. */
export const DELETED_VENDOR_OVERLAY_IDS: readonly string[] = [
  "por11", // CNL, fresh invaded zone
  "por12", // CNL, salt invaded zone
  "por13_aplc", // APS near-to-array
  "por13_fplc", // APS near-to-far
  "por14_aplc", // APS saltwater formation, near-to-array
  "por14_fplc", // APS saltwater formation, near-to-far
  "por16", // adnVISION675 azimuthal density neutron
  "por18", // EcoScope BPHI
  "por19", // EcoScope TNPH
  "por20_ta", // sonic-neutron, time-average sonic leg vs CNL response (DEC-080)
  "por20_fo", // sonic-neutron, field-observation sonic leg vs CNL response (DEC-080)
  "lith1_pek", // litho-density + NGS mineral ID, Pe vs K (DEC-081)
  "lith1_pethk", // litho-density + NGS mineral ID, Pe vs Th/K (DEC-081)
];

/**
 * Route-2 execution state (DEC-078). A derived overlay carries curves computed from
 * published equations and cited constants (`tools/gen-derived-overlays.mjs`, proven
 * against the digitized chart by `tools/chart-derivation.test.mjs`); resolution prefers
 * it, so the digitized coordinates for that id stop being read the moment the derivation
 * lands.
 *
 * - `por22_ta`: DERIVED (Wyllie time-average; constants stated on Por-22 p. 238 and
 *   Por-1 p. 212). Its mineral POINTS remain digitized pending their own derivation.
 * - `por22_fo`: DERIVED under DEC-079 as the PUBLISHED RHG-1980 ALGORITHM at the
 *   paper's stated constants (dtma 56/49/44, vf 5,300 ft/s) — deliberately NOT a
 *   replica of the printed curve, which is the paper's hand-drawn empirical transform
 *   that its own algorithms only approximate (they track it to ~1 us/ft below
 *   30 p.u. and depart by up to ~13 us/ft at 40 p.u.). The overlay therefore matches
 *   what IP / Geolog / Techlog compute rather than the chartbook tracing; the
 *   divergence is asserted, not hidden, in tools/chart-derivation.test.mjs.
 * - `lith3` / `lith4`: DERIVED under DEC-079 from Gardner & Dumanoir 1980's published
 *   litho-density physics (U = Pe·rho_e mixing volumetrically, rho_e from the eq-5
 *   calibration) with the paper's printed mineral table and the Lith-5 legend's fluid
 *   pairs. The printed charts are Platform Express TLD TOOL charts carrying a small
 *   tool-window slope the physics does not (<= 0.07 Pe, ~1% of the axis); Jauhar
 *   ruled the physics replaces the digitized legs regardless. Density legs are exact.
 * - `lith6_mid`: DERIVED (ternary geometry from Appendix B constants); the
 *   apparent-position mineral points and annotation arrows stay digitized.
 * - `lith2_thk`: DERIVED — the six Th/K boundary lines are geometry from the chart
 *   page's OWN printed values (p. 194 labels every line: Th/K = 25/12/3.5/2.0/0.6/0.3),
 *   proven one-to-one against the digitized lines; the published classification is
 *   Quirein et al., SPE 11143 (1982) Fig. 2, after Hassan, Hossin & Combaz, SPWLA 1976.
 *   The dashed clay/feldspar lines and the region label points stay digitized behind
 *   the pinned keep-list: no paper in the cited chain prints numeric per-mineral
 *   values — the chain was exhausted the same day (see the DEC-081/082 note above).
 */
export function resolveChartOverlay(id: string): ChartOverlayDef | undefined {
  const base = findChartOverlay(id);
  if (!base) return undefined;
  const derived = DERIVED_CHART_OVERLAYS.find((d) => d.id === id);
  if (!derived) return base;
  const resolved: ChartOverlayDef = { ...base };
  if (derived.curves) resolved.curves = derived.curves;
  if (derived.points) {
    // Same-label derived points replace their digitized twins; points not yet derived
    // (apparent-position minerals) stay digitized, recorded in the generator's notes.
    resolved.points = (base.points ?? []).map(
      (point) => derived.points!.find((d) => d.label === point.label) ?? point,
    );
  }
  if (derived.lines) {
    // Derived geometry replaces the digitized lines wholesale; only the annotation
    // labels the generator explicitly keeps survive from the digitized set.
    const keep = derived.keepDigitizedLineLabels ?? [];
    resolved.lines = [
      ...derived.lines,
      ...(base.lines ?? []).filter((line) => line.label !== undefined && keep.includes(line.label)),
    ];
  }
  return resolved;
}

/** The overlay catalog in its stable UI order, with derived curves shadowing digitized ones. */
export function allChartOverlays(): ChartOverlayDef[] {
  return CHART_OVERLAYS.map((def) => resolveChartOverlay(def.id) ?? def);
}
