// GENERATED by tools/gen-derived-overlays.mjs - DO NOT HAND-EDIT; re-run the generator.
// SB-PLT-024 route 2 (DEC-078): equation-derived overlay curves replacing digitized
// coordinates. The equations, cited constants and the digitized-agreement proof live
// in the generator and tools/chart-derivation.test.mjs.
import type { OverlayCurve } from "./chartOverlays";

export interface DerivedOverlay { id: string; curves: OverlayCurve[] }

export const DERIVED_CHART_OVERLAYS: DerivedOverlay[] = [
  {
    id: "por22_ta",
    curves: [
      { name: "Quartz sandstone", labelEvery: 10, grads: [[0,55.5556,2.65],[5,62.2278,2.5675],[10,68.9,2.485],[15,75.5722,2.4025],[20,82.2444,2.32],[25,88.9167,2.2375],[30,95.5889,2.155],[35,102.2611,2.0725],[40,108.9333,1.99],[45,115.6056,1.9075]] },
      { name: "Calcite (limestone)", labelEvery: 10, grads: [[0,47.619,2.71],[5,54.6881,2.6245],[10,61.7571,2.539],[15,68.8262,2.4535],[20,75.8952,2.368],[25,82.9643,2.2825],[30,90.0333,2.197],[35,97.1024,2.1115],[40,104.1714,2.026],[45,111.2405,1.9405]] },
      { name: "Dolomite", labelEvery: 10, grads: [[0,43.4783,2.87],[5,50.7543,2.7765],[10,58.0304,2.683],[15,65.3065,2.5895],[20,72.5826,2.496],[25,79.8587,2.4025],[30,87.1348,2.309],[35,94.4109,2.2155],[40,101.687,2.122],[45,108.963,2.0285]] },
    ],
  },
];
