/**
 * Chart-overlay distribution policy — DEC-078 (2026-08-19), SB-PLT-024.
 *
 * NOT generated. `chartOverlays.ts` is generated by `tools/chartdig` and must never be
 * hand-edited; this module is the hand-maintained policy register beside it.
 *
 * Jauhar's ruling on the 19 vendor-derived chart definitions (docs/takeover/DECISIONS.md
 * DEC-078; register history in docs/IP_PROVENANCE.md §2.1):
 *
 * - The DERIVABLE definitions (everything not listed below) are to be independently
 *   re-derived from primary publications and cited physical constants — the published
 *   Wyllie time-average and Raymer-Hunt-Gardner equations for por20/por22, and the
 *   Appendix-B-cited mineral constants + volumetric U-mixing for the lithology charts —
 *   replacing the digitized coordinates as each re-derivation is executed and verified.
 *
 * - The TOOL-RESPONSE definitions listed here have NO independent primary source: each
 *   curve is the vendor's own tool characterization, published nowhere but the chartbook,
 *   so re-derivation is impossible in principle. Ruled RETAINED, cited and fail-closed
 *   (SB-PLT-023), THROUGH GATE 5 — they are needed for manual/field verification — with
 *   the delete kept a single named operation for final commercial packaging.
 *
 * THE DELETE, when Jauhar says so: regenerate `chartOverlays.ts` with `tools/chartdig`
 * omitting exactly the ids below (or delete their entries), then delete this list. The
 * overlay picker and renderer already tolerate an absent id — nothing else changes.
 */
export const TOOL_RESPONSE_OVERLAY_IDS: readonly string[] = [
  "por11", // CNL, fresh invaded zone
  "por12", // CNL, salt invaded zone
  "por13_aplc", // APS near-to-array
  "por13_fplc", // APS near-to-far
  "por14_aplc", // APS saltwater formation, near-to-array
  "por14_fplc", // APS saltwater formation, near-to-far
  "por16", // adnVISION675 azimuthal density neutron
  "por18", // EcoScope BPHI
  "por19", // EcoScope TNPH
];

/** True for a chart definition that exists only as a vendor tool characterization. */
export function isToolResponseOverlay(id: string): boolean {
  return TOOL_RESPONSE_OVERLAY_IDS.includes(id);
}
