// GENERATED by tools/gen-derived-overlays.mjs - DO NOT HAND-EDIT; re-run the generator.
// SB-PLT-024 route 2 (DEC-078): equation-derived overlay data replacing digitized
// coordinates. The equations, cited constants and the digitized-agreement proof live
// in the generator and tools/chart-derivation.test.mjs.
import type { OverlayCurve, OverlayLine, OverlayPoint } from "./chartOverlays";

export interface DerivedOverlay {
  id: string;
  curves?: OverlayCurve[];
  /** Replace same-label digitized points only; unmatched digitized points stay. */
  points?: OverlayPoint[];
  /** Replace the digitized lines wholesale, except labels listed below. */
  lines?: OverlayLine[];
  keepDigitizedLineLabels?: string[];
}

export const DERIVED_CHART_OVERLAYS: DerivedOverlay[] = [
  {
    id: "por22_ta",
    curves: [
      { name: "Quartz sandstone", labelEvery: 10, grads: [[0,55.5556,2.65],[5,62.2278,2.5675],[10,68.9,2.485],[15,75.5722,2.4025],[20,82.2444,2.32],[25,88.9167,2.2375],[30,95.5889,2.155],[35,102.2611,2.0725],[40,108.9333,1.99],[45,115.6056,1.9075]] },
      { name: "Calcite (limestone)", labelEvery: 10, grads: [[0,47.619,2.71],[5,54.6881,2.6245],[10,61.7571,2.539],[15,68.8262,2.4535],[20,75.8952,2.368],[25,82.9643,2.2825],[30,90.0333,2.197],[35,97.1024,2.1115],[40,104.1714,2.026],[45,111.2405,1.9405]] },
      { name: "Dolomite", labelEvery: 10, grads: [[0,43.4783,2.87],[5,50.7543,2.7765],[10,58.0304,2.683],[15,65.3065,2.5895],[20,72.5826,2.496],[25,79.8587,2.4025],[30,87.1348,2.309],[35,94.4109,2.2155],[40,101.687,2.122],[45,108.963,2.0285]] },
    ],
  },
  {
    id: "por22_fo",
    curves: [
      { name: "Quartz sandstone", labelEvery: 10, grads: [[0,56.0224,2.65],[5,61.0701,2.5675],[10,66.7178,2.485],[15,73.0373,2.4025],[20,80.1025,2.32],[25,87.9846,2.2375],[30,96.7445,2.155],[35,106.4212,2.0725]] },
      { name: "Calcite (limestone)", labelEvery: 10, grads: [[0,48.7805,2.71],[5,53.2872,2.6245],[10,58.3601,2.539],[15,64.0769,2.4535],[20,70.5219,2.368],[25,77.7832,2.2825],[30,85.9476,2.197],[35,95.0909,2.1115],[40,123.6428,2.026]] },
      { name: "Dolomite", labelEvery: 10, grads: [[0,43.956,2.87],[5,48.0841,2.7765],[10,52.7496,2.683],[15,58.032,2.5895],[20,64.0205,2.496],[25,70.8121,2.4025],[30,78.5083,2.309],[35,87.2077,2.2155],[40,119.0294,2.122]] },
    ],
  },
  {
    id: "lith6_mid",
    points: [{ x: 4.8, y: 2.65, label: "Quartz" }, { x: 13.8, y: 2.71, label: "Calcite" }, { x: 9, y: 2.87, label: "Dolomite" }, { x: 15, y: 2.98, label: "Anhydrite" }],
    lines: [
      { pts: [[4.8,2.65],[13.8,2.71]], label: "% calcite" },
      { pts: [[9,2.87],[4.8,2.65]], label: "% quartz" },
      { pts: [[13.8,2.71],[9,2.87]], label: "% dolomite" },
      { pts: [[12,2.698],[8.16,2.826]] },
      { pts: [[10.2,2.686],[7.32,2.782]] },
      { pts: [[8.4,2.674],[6.48,2.738]] },
      { pts: [[6.6,2.662],[5.64,2.694]] },
      { pts: [[6.6,2.662],[9.96,2.838]] },
      { pts: [[8.4,2.674],[10.92,2.806]] },
      { pts: [[10.2,2.686],[11.88,2.774]] },
      { pts: [[12,2.698],[12.84,2.742]] },
      { pts: [[5.64,2.694],[12.84,2.742]] },
      { pts: [[6.48,2.738],[11.88,2.774]] },
      { pts: [[7.32,2.782],[10.92,2.806]] },
      { pts: [[8.16,2.826],[9.96,2.838]] },
    ],
    keepDigitizedLineLabels: ["Heavy minerals", "Gas direction", "Salt", "Barite"],
  },
];
