/**
 * Chart-overlay distribution policy — DEC-078 (2026-08-19), SB-PLT-024.
 *
 * NOT generated. `chartOverlays.ts` is generated by `tools/chartdig` and must never be
 * hand-edited; this module is the hand-maintained policy register beside it.
 *
 * Jauhar's ruling on the 19 vendor-derived chart definitions (docs/takeover/DECISIONS.md
 * DEC-078; register history in docs/IP_PROVENANCE.md §2.1):
 *
 * - The DERIVABLE definitions (everything not listed below) are to be independently
 *   re-derived from primary publications and cited physical constants — the published
 *   Wyllie time-average and Raymer-Hunt-Gardner equations for por22, and the
 *   paper-cited mineral constants + volumetric U-mixing for the lithology charts —
 *   replacing the digitized coordinates as each re-derivation is executed and verified.
 *
 * - The TOOL-RESPONSE definitions listed here have NO independent primary source: each
 *   curve is the vendor's own tool characterization, published nowhere but the chartbook,
 *   so re-derivation is impossible in principle. Ruled RETAINED, cited and fail-closed
 *   (SB-PLT-023), THROUGH GATE 5 — they are needed for manual/field verification — with
 *   the delete kept a single named operation for final commercial packaging.
 *   DEC-080 moved por20_ta/por20_fo into this class (CNL-coupled neutron axis), so the
 *   register holds ELEVEN ids and the derivable class holds eight definitions.
 *
 * THE DELETE, when Jauhar says so: regenerate `chartOverlays.ts` with `tools/chartdig`
 * omitting exactly the ids below (or delete their entries), then delete this list. The
 * overlay picker and renderer already tolerate an absent id — nothing else changes.
 */
import { CHART_OVERLAYS, findChartOverlay, type ChartOverlayDef } from "./chartOverlays";
import { DERIVED_CHART_OVERLAYS } from "./chartOverlaysDerived.gen";

export const TOOL_RESPONSE_OVERLAY_IDS: readonly string[] = [
  "por11", // CNL, fresh invaded zone
  "por12", // CNL, salt invaded zone
  "por13_aplc", // APS near-to-array
  "por13_fplc", // APS near-to-far
  "por14_aplc", // APS saltwater formation, near-to-array
  "por14_fplc", // APS saltwater formation, near-to-far
  "por16", // adnVISION675 azimuthal density neutron
  "por18", // EcoScope BPHI
  "por19", // EcoScope TNPH
  // DEC-080 (2026-08-19): Por-20 reclassified INTO this class. Its sonic coordinates
  // are derivable (Wyllie/RHG), but every non-limestone curve's NEUTRON coordinate is
  // the CNL tool response — the same vendor characterization as por11 — so a
  // half-derived chart stays vendor-encumbered in every coordinate pair. Jauhar ruled
  // no half-measures: both defs join the retained class and the Gate 5 decision.
  "por20_ta", // sonic-neutron, time-average sonic leg vs CNL response
  "por20_fo", // sonic-neutron, field-observation sonic leg vs CNL response
];

/** True for a chart definition that exists only as a vendor tool characterization. */
export function isToolResponseOverlay(id: string): boolean {
  return TOOL_RESPONSE_OVERLAY_IDS.includes(id);
}

/**
 * Route-2 execution state (DEC-078). A derived overlay carries curves computed from
 * published equations and cited constants (`tools/gen-derived-overlays.mjs`, proven
 * against the digitized chart by `tools/chart-derivation.test.mjs`); resolution prefers
 * it, so the digitized coordinates for that id stop being read the moment the derivation
 * lands — the superseded bytes leave `chartOverlays.ts` at the next chartdig regeneration,
 * together with whatever the Gate 5 nine-id decision removes.
 *
 * - `por22_ta`: DERIVED (Wyllie time-average; constants stated on Por-22 p. 238 and
 *   Por-1 p. 212). Its mineral POINTS remain digitized pending their own derivation.
 * - `por22_fo`: DERIVED under DEC-079 as the PUBLISHED RHG-1980 ALGORITHM at the
 *   paper's stated constants (dtma 56/49/44, vf 5,300 ft/s) — deliberately NOT a
 *   replica of the printed curve, which is the paper's hand-drawn empirical transform
 *   that its own algorithms only approximate (they track it to ~1 us/ft below
 *   30 p.u. and depart by up to ~13 us/ft at 40 p.u.). The overlay therefore matches
 *   what IP / Geolog / Techlog compute rather than the chartbook tracing; the
 *   divergence is asserted, not hidden, in tools/chart-derivation.test.mjs.
 * - `lith3` / `lith4`: DERIVED under DEC-079 from Gardner & Dumanoir 1980's published
 *   litho-density physics (U = Pe·rho_e mixing volumetrically, rho_e from the eq-5
 *   calibration) with the paper's printed mineral table and the Lith-5 legend's fluid
 *   pairs. The printed charts are Platform Express TLD TOOL charts carrying a small
 *   tool-window slope the physics does not (<= 0.07 Pe, ~1% of the axis); Jauhar
 *   ruled the physics replaces the digitized legs regardless. Density legs are exact.
 * - `lith2_thk`: DERIVED — the six Th/K boundary lines are geometry from the chart
 *   page's OWN printed values (p. 194 labels every line: Th/K = 25/12/3.5/2.0/0.6/0.3),
 *   proven one-to-one against the digitized lines; the published classification is
 *   Quirein et al., SPE 11143 (1982) Fig. 2, after Hassan, Hossin & Combaz, SPWLA 1976.
 *   The dashed clay/feldspar lines and the region label points stay digitized behind
 *   the pinned keep-list: neither paper prints numeric per-mineral values (figures
 *   only) — the numeric table is Edmundson & Raymer 1979, not yet obtained.
 */
export function resolveChartOverlay(id: string): ChartOverlayDef | undefined {
  const base = findChartOverlay(id);
  if (!base) return undefined;
  const derived = DERIVED_CHART_OVERLAYS.find((d) => d.id === id);
  if (!derived) return base;
  const resolved: ChartOverlayDef = { ...base };
  if (derived.curves) resolved.curves = derived.curves;
  if (derived.points) {
    // Same-label derived points replace their digitized twins; points not yet derived
    // (apparent-position minerals) stay digitized, recorded in the generator's notes.
    resolved.points = (base.points ?? []).map(
      (point) => derived.points!.find((d) => d.label === point.label) ?? point,
    );
  }
  if (derived.lines) {
    // Derived geometry replaces the digitized lines wholesale; only the annotation
    // labels the generator explicitly keeps survive from the digitized set.
    const keep = derived.keepDigitizedLineLabels ?? [];
    resolved.lines = [
      ...derived.lines,
      ...(base.lines ?? []).filter((line) => line.label !== undefined && keep.includes(line.label)),
    ];
  }
  return resolved;
}

/** The overlay catalog in its stable UI order, with derived curves shadowing digitized ones. */
export function allChartOverlays(): ChartOverlayDef[] {
  return CHART_OVERLAYS.map((def) => resolveChartOverlay(def.id) ?? def);
}
