// SB-CORE-044 (DEC-083): the fail-closed release-inventory proof over the settled
// shipped set. Engineering cannot supply legal clearance; what it CAN prove is that
// every digitized vendor payload in the tree is registered by name in the provenance
// register, that the DEC-083 first-sale deferral stands in every store that carries
// it, and that the public chart claim states what actually ships. Each assertion is
// two-sided: the sweep must find something, the stale claim must be absent AND the
// current claim present, the deferral must name its assets.
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (...p) => fs.readFileSync(path.join(repo, ...p), "utf8");

// Digitized payloads are marked by construction: every file tools/chartdig emits
// carries this banner, so the tree enumerates itself and a new digitized file
// cannot ship unregistered without turning this suite red.
const DIGITIZED_BANNER = "GENERATED by tools/chartdig";

function sweepForBanner(root) {
  const hits = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "node_modules" || entry.name === "target") continue;
        walk(full);
      } else if (/\.(ts|rs|mjs|js)$/u.test(entry.name)) {
        if (fs.readFileSync(full, "utf8").includes(DIGITIZED_BANNER)) hits.push(entry.name);
      }
    }
  };
  walk(path.join(repo, root));
  return hits;
}

test("every_chartdig_digitized_asset_in_the_tree_is_registered_by_name_in_the_provenance_register", () => {
  const found = [...sweepForBanner("src"), ...sweepForBanner("src-tauri/src")].sort();
  // The sweep finding NOTHING would mean the banner convention broke, not that the
  // tree is clean — the known shipped assets pin the enumerator itself.
  assert.deepEqual(found, ["chartOverlays.ts", "neutron_charts.rs"],
    "the digitized-payload sweep must find exactly the known shipped assets; " +
    "a new hit must be registered in docs/IP_PROVENANCE.md and added here deliberately");
  const register = read("docs", "IP_PROVENANCE.md");
  for (const file of found) {
    assert.ok(register.includes(file),
      `digitized asset ${file} ships but is not named in docs/IP_PROVENANCE.md`);
  }
});

test("the_dec_083_first_sale_deferral_is_recorded_in_every_store_and_cannot_silently_vanish", () => {
  const decisions = read("docs", "takeover", "DECISIONS.md");
  const dec083 = decisions.split("\n").find((line) => line.startsWith("| DEC-083 |"));
  assert.ok(dec083, "DECISIONS.md must carry the DEC-083 row");
  assert.ok(dec083.includes("first commercial sale"), "DEC-083 must defer to first commercial sale");
  assert.ok(dec083.includes("neutron_charts.rs"),
    "DEC-083 must name the Por-4/Por-5 equivalence tables in the deferred set");
  assert.ok(dec083.includes("NOT legal clearance"),
    "DEC-083 must state it is a pre-ship posture, not legal clearance");

  const claims = read("docs", "takeover", "CLAIMS.md");
  for (const id of ["CLAIM-012", "CLAIM-013"]) {
    const row = claims.split("\n").find((line) => line.startsWith(`| ${id} |`));
    assert.ok(row, `CLAIMS.md must carry the ${id} row`);
    assert.ok(row.includes("LEGAL-REVIEW"), `${id} must remain LEGAL-REVIEW until counsel rules`);
    assert.ok(row.includes("first-sale blocker"), `${id} must remain a named first-sale blocker`);
    assert.ok(row.includes("DEC-083"), `${id} must record the DEC-083 deferral`);
  }

  const packet = read("docs", "takeover", "GATE2_BLOCKERS.md");
  assert.ok(packet.includes("first-sale deferred register"),
    "the blocker packet must carry the deferred register");
  for (const name of ["CLAIM-012", "CLAIM-013", "neutron_charts.rs"]) {
    assert.ok(packet.includes(name), `the deferred register must name ${name}`);
  }
});

test("the_public_chart_claim_states_what_actually_ships_and_the_stale_digitized_claim_never_returns", () => {
  const readme = read("README.md");
  assert.ok(!readme.includes("vector-digitized"),
    "the pre-DEC-082 claim of shipping digitized chart overlays must never return to README");
  const claim = readme.match(/\*\*(\d+) chart overlays re-derived from published primary sources\*\*/u);
  assert.ok(claim, "README must carry the derived-overlay claim in its exact form");

  const catalog = read("src", "ui", "chartOverlays.ts");
  const shipped = [...catalog.matchAll(/^ {4}id: "([a-z0-9_]+)"/gmu)].map((m) => m[1]);
  assert.equal(Number(claim[1]), shipped.length,
    "the README-claimed overlay count must equal the shipped catalog count");
  assert.ok(shipped.length > 0, "the shipped catalog must not be empty");
});
